title: Timur Iskhakov
url: "https://timiskhakov.github.io"

theme: minima
show_excerpts: true
permalink: /posts/:title
plugins:
  - jekyll-feed
  - jekyll-katex
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
