title: Timur Iskhakov
description: Programming notes
email: timiskhakov@gmail.com
baseurl: ""
url: "https://timiskhakov.github.io"
github_username: timiskhakov
linkedin_username: timiskhakov

theme: minima
permalink: /posts/:title
plugins:
  - jekyll-feed
  - jekyll-katex
